import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Ricky And Morty",
  description: "Generated by Adem ALKAN",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#e4a788]`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
